### ISSUE TITLE
Download is too large

### ISSUE THREAD

**Issue by Jellby** [nemequ/pgi-travis#2]
I was trying to update a docker image (bulit inside a virtual machine in GitLab CI) with PGI, and got this error:

```
Installing PGI version 19.10 into /root/pgi
Installing module files for PGI linux86-64 version(s): 19.10 2019
Done
NOTICE: A COMMUNITY 19.10 license key has been installed at:
            /root/pgi/license.dat
Error processing tar file(exit status 1): write /tmp/install_components/pgicuda.tar.gz: no space left on device
```

Is there any possibility of skipping the components that I won't install anyway?

**Comment by nemequ** [comment]
Not really, sorry.  It's a single giant tarball.  We already extract it as it is downloaded instead of writing to disk to save space.

You might be able to use tar's `--exclude` argument to prevent the tar from extracting component(s) you don't need.  I don't now what those files are, and I don't know if PGI's installer will work without them (there may be some sort of integrity check which would cause it to fail).

Another possibility would be extracting the installer to a directory mounted with tmpfs; there is no reason to keep the installer around after installation, so you can just unmount it when you're done.

I don't know what your workflow is like, but you could also download and extract the installer *outside* of Docker.  When you're building the image just mount the directory with the installer as a volume in Docker and run the installation commands (should be easy enough to pull out of this script).  That way the installer doesn't use any space at all in the installer.

**Comment by Jellby** [comment]
For the record, I had success using the following in my `Dockerfile`:

    wget -q -O /dev/stdout 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh' | \
        sed 's/zxf/zx --exclude=*\/pgicuda* -f/' | /bin/sh && \
    rm -rf /tmp/*

to get docker image with the compiler and reduced size, which can be built inside GitLab's shared runners.

PS. Note that removing `/tmp` itself will cause the compiler to hang with no message.
